### ISSUE TITLE
100vw width causes overflow

### ISSUE THREAD

**Issue by Haroenv** [thibmaek/silentschiedam#29]
There are a few (4) moments where a `width: 100vw` is declared. This causes a horizontal overflow the width of the padding/margin. This can be solved by using `100%`  in those cases.

**Comment by thibmaek** [comment]
Is this on mobile or desktop?

**Comment by Haroenv** [comment]
Desktop chrome on Windows, visible in navy for example

**Comment by thibmaek** [comment]
This is pretty much a non-issue since there is no use for the application on desktop.
Application was tested to support at least iPhone 4 on mobile platforms so it should be no issue there, if it is let me know if you bump into one. Closing this for now, will reopen if there is one.
